import test from 'node:test';
import assert from 'node:assert/strict';
import {parseBook,splitSegments,clampPosition,nextPosition,bookProgress,chooseVoice,localChineseVoices,SpeechPlayer,SAMPLE} from '../dist/core.js';
const local={name:'Chinese local',voiceURI:'local-zh',lang:'zh-HK',localService:true};
function fixture(text='第一章 開始\n甲乙。\n丙丁。\n第二章 結尾\n最後一段。'){
 const utterances=[];const timers=new Map();let timerId=0;const errors=[];let voice=local;
 const synth={cancel(){if(this.synchronousCancel&&utterances.length)utterances.at(-1).onerror?.({error:'canceled'});},speak(u){utterances.push(u);}};
 const player=new SpeechPlayer({synth,Utterance:class{constructor(text){this.text=text;}},getVoice:()=>voice,getRate:()=>1,onError:m=>errors.push(m),setTimer:fn=>{timers.set(++timerId,fn);return timerId;},clearTimer:id=>timers.delete(id)});
 player.load(parseBook(text));return{player,synth,utterances,timers,errors,setVoice:v=>voice=v};
}
test('recognizes Chinese and English headings, BOM, CRLF and Markdown headings',()=>{const b=parseBook('\uFEFF前面的話\r\n第一章 起點\r\n內容\r\n## 第 12 回　回家\r\n你好\r\nChapter 3 Finale\r\n結束','書.txt');assert.equal(b.title,'書');assert.deepEqual(b.chapters.map(c=>c.title),['開始閱讀','第一章 起點','第 12 回　回家','Chapter 3 Finale']);});
test('original sample has three chapters',()=>assert.equal(parseBook(SAMPLE).chapters.length,3));
test('unheaded and empty-heading books are still readable',()=>{assert.equal(parseBook('只有文字').chapters.length,1);assert.equal(parseBook('第一章').count,1);});
test('rejects empty, corrupt and oversized imports',()=>{assert.throws(()=>parseBook('  \n'));assert.throws(()=>parseBook('�'.repeat(20)));assert.throws(()=>parseBook('中'.repeat(8000001)));});
test('chunks bounded without breaking surrogate pairs',()=>{const text=('中文🙂'.repeat(250))+'。';const pieces=splitSegments(text);assert.equal(pieces.map(p=>p.text).join(''),text);assert.ok(pieces.every(p=>p.text.length<=140&&!/^[\uDC00-\uDFFF]|[\uD800-\uDBFF]$/.test(p.text)));});
test('chapter traversal and clamped restore',()=>{const b=parseBook('第一章\na\nb\n第二章\nc');assert.deepEqual(nextPosition(b,{chapter:0,segment:1}),{chapter:1,segment:0});assert.deepEqual(nextPosition(b,{chapter:1,segment:0},-1),{chapter:0,segment:1});assert.equal(nextPosition(b,{chapter:1,segment:0}),null);assert.deepEqual(clampPosition(b,{chapter:99,segment:-7}),{chapter:1,segment:0});assert.equal(bookProgress(b,{chapter:1,segment:0},true),100);});
test('voice gate never picks a remote or non-Chinese voice',()=>{const remote={...local,voiceURI:'remote',localService:false};assert.equal(chooseVoice([remote]),null);assert.equal(chooseVoice([remote,local],'remote'),local);assert.deepEqual(localChineseVoices([{...local,lang:'en-US'},local]),[local]);assert.equal(chooseVoice([{...local,localService:undefined}]),null);});
test('natural ends advance continuously and final end ends exactly once',()=>{const f=fixture();f.player.play();assert.equal(f.utterances.length,1);f.utterances[0].onstart();assert.equal(f.player.state,'playing');f.utterances[0].onend();assert.equal(f.player.pos.segment,1);f.utterances[1].onend();assert.equal(f.player.pos.chapter,1);f.utterances[2].onend();assert.equal(f.player.state,'ended');f.utterances[2].onend();assert.equal(f.utterances.length,3);assert.equal(f.timers.size,0);});
test('stale synchronous cancellation errors and delayed ends cannot advance',()=>{const f=fixture();f.synth.synchronousCancel=true;f.player.play();const old=f.utterances[0];f.player.pause();old.onend();old.onerror({error:'canceled'});assert.equal(f.player.state,'paused');assert.equal(f.player.pos.segment,0);assert.equal(f.errors.length,0);});
test('rapid play/pause/seek makes stale callbacks inert',()=>{const f=fixture();f.player.play();const a=f.utterances[0];f.player.pause();f.player.play();const b=f.utterances[1];f.player.seek({chapter:1,segment:0},true);a.onstart();a.onend();b.onend();assert.equal(f.player.pos.chapter,1);assert.equal(f.utterances.length,3);});
test('new book invalidates callbacks',()=>{const f=fixture();f.player.play();const old=f.utterances[0];f.player.load(parseBook('新書'));old.onend();assert.equal(f.player.book.title,'未命名的書');assert.equal(f.player.book.chapters[0].segments[0].text,'新書');assert.equal(f.player.state,'idle');});
test('pause resumes at boundary with correct base on repeated resumes',()=>{const f=fixture('甲乙丙丁戊己庚辛');f.player.play();f.utterances[0].onboundary({charIndex:2});f.player.pause();f.player.play();assert.equal(f.utterances[1].text,'丙丁戊己庚辛');f.utterances[1].onboundary({charIndex:2});f.player.pause();f.player.play();assert.equal(f.utterances[2].text,'戊己庚辛');});
test('a missing voice stops without remote fallback or skipped text',()=>{const f=fixture();f.player.play();f.setVoice(null);f.utterances[0].onend();assert.equal(f.player.pos.segment,1);assert.equal(f.player.state,'paused');assert.equal(f.utterances.length,1);assert.equal(f.errors.length,1);});
test('watchdog preserves location, requires manual retry and clears timeout',()=>{const f=fixture();f.player.play();[...f.timers.values()][0]();assert.equal(f.player.state,'paused');assert.equal(f.player.pos.segment,0);assert.equal(f.utterances.length,1);assert.equal(f.timers.size,0);});
test('stop before final onend does not finish and subsequent play restarts segment',()=>{const f=fixture('只有一段');f.player.play();const old=f.utterances[0];f.player.stop();old.onend();assert.equal(f.player.state,'idle');f.player.play();assert.equal(f.utterances[1].text,'只有一段');});
test('ended book restarts only on explicit Play',()=>{const f=fixture('只有一段');f.player.play();f.utterances[0].onend();assert.equal(f.player.state,'ended');f.player.play();assert.equal(f.utterances.length,2);assert.equal(f.player.pos.segment,0);});
